### PR TITLE
Chat feature

### PR DESCRIPTION
**Pull request by justvinny**

### CODE REVIEW

**Review by Jadatu13 — CHANGES_REQUESTED** [review]
When attempting to run the branch on my own personal machine I receive a building javascript bundle error.

image

**Comment by justvinny** [comment]
> 
> 
> When attempting to run the branch on my own personal machine I receive a building javascript bundle error.
> 
> ran `npm install` but still having issues.
> 
> image

Try clearing you expo cache when starting.

`expo start -c`

Then reload once you connect to your device with key 'R'.

**Review by Jadatu13 — CHANGES_REQUESTED** [review]
Chat functionality works perfectly on my web test, the logbox error has been removed.

However when testing on my iOS device I am unable to get past building JavaScript bundle.
I have attempted to `npm install` and `expo start -c` however this has not fixed any issue & the problem still occurs.

IMG_4512

**Review by Jadatu13 — APPROVED** [review]
Everything functions as expected on both mobile and web without errors.

**Pull request merged**
